### ISSUE TITLE
Compile PHP-GTK3 to windows with PHP 8.1.14

### ISSUE THREAD

**Issue by scorninpc** [scorninpc/php-gtk3#26]
We need to compile all platforms on the same PHP version

I think the PHP 8.1.14 is alot stable

thanks @subabrain for the tutorial and a lot time spent to make this possible

**Comment by subabrain** [comment]
Hi,

ok - thanks!

there are some problems with phpcpp as mentioned by you - but i will get it soon :)

Greets
Robert

**Comment by scorninpc** [comment]
Ok, relax. People are downloading the 7.3 version and testings. Its very nice to find bugs and fix

**Comment by subabrain** [comment]
ok,

one thing - can you please contact them https://gtk.php.net/download.php?language=en-US - to take phpgtk3 for windows on there site?

Thanks and Greets!
Robert

**Comment by scorninpc** [comment]
> one thing - can you please contact them https://gtk.php.net/download.php?language=en-US - to take phpgtk3 for windows on their site?

I've done this one time, and we cannot do that becase we use PHP-CPP

Another problem, is that php-gtk are no auto-generated code, so alot of GTK methods are missing

**Comment by subabrain** [comment]
hi,

ok i see - happy new year to you and all others :)

Greets
Robert

**Comment by scorninpc** [comment]
Hello @subabrain

i'm trying to close this issue, but i think its not looking for adicional includes. Look how I configure

![image](https://user-images.githubusercontent.com/2607849/218276275-03857fb3-91dc-48ed-b43e-3e193a1a512f.png)

But still not find phpcpp.h

@apss-pohl any idea? i'm following the documentation

**Comment by apss-pohl** [comment]
I tried to compile 8 in friday but also struggled. I might be close to success. Maybe i can comeup with Something next week.

**Comment by scorninpc** [comment]
but i'm stuck on this additional include, also on php 7. Any advice?

**Comment by scorninpc** [comment]
I've done without error

![image](https://user-images.githubusercontent.com/2607849/218291359-d5cb1c04-b983-43ea-8819-b50edfb34eb2.png)

But I cannot run:


added extension to php.ini

![image](https://user-images.githubusercontent.com/2607849/218291378-ac58f3b7-3b45-47c1-b61c-b722118c505d.png)

added correct extension dir

![image](https://user-images.githubusercontent.com/2607849/218291393-1626eba1-c248-4bb5-8d73-5f94fce51ff4.png)

changed file name and added on ext dir

![image](https://user-images.githubusercontent.com/2607849/218291414-702a0514-9b10-4751-a176-7bf1b3ebbaaf.png)

but when i run, nothing ...

![image](https://user-images.githubusercontent.com/2607849/218291424-66d3d75d-cdd3-478f-bc67-867b0ab346e9.png)

I cannot work without error LOL

Any advice

**Comment by scorninpc** [comment]
Ok guys, this is a good news!

![image](https://user-images.githubusercontent.com/2607849/218325435-67a1d672-8279-49a7-8dc6-adfeaa4463b4.png)

I don't know what I would do without persistence of @subabrain to make this work, and @apss-pohl for improvements! Thank you guys

**Comment by scorninpc** [comment]
Done https://github.com/scorninpc/php-gtk3/releases/tag/0.13-beta

Now windows and linux has the same version

**Comment by apss-pohl** [comment]
Great success! 
I reviewd you new tutorial, for me everything looks more or less the same what i tried last week but i still fail (I treid 8.2.14, so this could also be the reason. Will try 8.1 today).
The link to the PR of PHP-CPP is just the overview, which one did you try? 
I forked the repo and took the commits from this one:
https://github.com/CopernicaMarketingSoftware/PHP-CPP/issues/506

Adding the stuff @subabrain figured out. It can be found here:
https://github.com/apss-pohl/PHP-CPP-win/tree/fork

So maybe i need to merge another PR?
It's a mess when it comes to PHP-CPP..

**Comment by scorninpc** [comment]
> I reviewd you new tutorial, for me everything looks more or less the same what i tried last week but i still fail (I treid 8.2.14, so this could also be the reason. Will try 8.1 today).

And what do you think about organization? i agree that no one with less understand about Visual Studio will try this, but, do you think anyone that read this can compile?

> The link to the PR of PHP-CPP is just the overview, which one did you try?

This is a pain. The guy who maintain php-cpp @EmielBruijntjes, need add more people to team, or this project will die. I'm sad about that. The devs liked his project, and try to maintain that, but with alot PR open, is a pain to merge manualy


> I forked the repo and took the commits from this one: [CopernicaMarketingSoftware/PHP-CPP#506](https://github.com/CopernicaMarketingSoftware/PHP-CPP/issues/506)
> 
> Adding the stuff @subabrain figured out. It can be found here: https://github.com/apss-pohl/PHP-CPP-win/tree/fork

Thats what I done! Got this repo, and add @subabrain changes. I think that doesn't have on tutorial, is about C compile version. Need to change C++ to 17, but also C to 17 too
